<?php 
	if (!$_POST) {
		$last_modified = filemtime(__FILE__);
		if (!$_POST && isset($_SERVER['HTTP_IF_MODIFIED_SINCE'])) {
			if ($last_modified <= strtotime($_SERVER['HTTP_IF_MODIFIED_SINCE'])) {
				header("HTTP/1.1 304 Not Modified");
				exit();
			}
		}
		header("Last-Modified: ".date(DATE_COOKIE,$last_modified));
		header("Cache-control: max-age=3600");		
	}	  
?>
<html>
	<head>
		<style type="text/css" media="screen, projection">	
			@import url(/theme.css);				
			@import url(/portlet.css);
		</style>		
	</head>
	<body> 
		<form method="post" id="default">
			<label>Name: </label><input name="name"/><br/>
			<label>Email: </label><input name="email"/><br/>
			<label>Message: </label><textarea name="message"></textarea><br/>
			<label>: </label><input type="submit"/>
		</form>
	</body>
</html>
